map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 5.5
raytrace_range: 6.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.15, -0.15], [-0.15, 0.15], [0.15, 0.15], [0.15, -0.15]]
footprint_padding: 0.25

plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: 3irobotix_lidar, data_type: LaserScan, topic: i3e_d3/laser/scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 5.5, raytrace_range: 6.0}

inflater_layer:
 inflation_radius: 0.6
