base_frame: base_footprint
odom_frame: odom
map_update_interval: 5.0
maxUrange: 4.0
maxRange: 8.0

minimumScore: 200

linearUpdate: 1.0
angularUpdate: 0.436
temporalUpdate: -1.0
resampleThreshold: 0.5
particles: 80
xmin: -1.0
xmax: -1.0
ymin: 1.0
ymax: 1.0

delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
