local_costmap:
   global_frame: odom
   #global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 5.0
   height: 5.0
   resolution: 0.15
   static_map: false
   rolling_window: true
